webtalk_init -webtalk_dir D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 22 19:41:52 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1266856" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "213169040_0_0_500" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "12e96b53-90a5-405c-a21d-05846ba64ec6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5c8bd872-de1d-4ed5-837e-b78089c0c30e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key cable -value "Digilent/Basys3/15000000" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0362D093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "13:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 50002828 -regid "213169040_0_0_500" -xml D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.hw/webtalk/usage_statistics_ext_labtool.xml -html D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.hw/webtalk/usage_statistics_ext_labtool.html -wdm D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
