# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.cache/wt [current_project]
set_property parent.project_path D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/sources_1/new/Generic_Counter.v
  D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/sources_1/new/Random_Colour.v
  D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/sources_1/new/VGA_Display.v
  D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/sources_1/new/Navigtaion_State_Machine.v
  D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/sources_1/new/Snkae_Control.v
  D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/sources_1/new/Score_Counter.v
  D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/sources_1/new/Master_State_Machine.v
  D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/sources_1/new/Random_Num.v
  D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/sources_1/new/Snake_Wrapper.v
}
read_xdc D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/constrs_1/new/Snake_XDC.xdc
set_property used_in_implementation false [get_files D:/Xilinx_Vivado_SDK_Win_2015.2_0626_1/New_Projects/Advanced_Snake/Advanced_Snake.srcs/constrs_1/new/Snake_XDC.xdc]

synth_design -top Snake_Wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef Snake_Wrapper.dcp
catch { report_utilization -file Snake_Wrapper_utilization_synth.rpt -pb Snake_Wrapper_utilization_synth.pb }
